### ISSUE TITLE
Package the AutoPilot project 

### ISSUE THREAD

**Issue by cschlegelmilch** [overstory/ml-monitoring-plugin#6]
<a href="https://github.com/chrisrhayes"><img src="https://avatars.githubusercontent.com/u/811737?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [chrisrhayes](https://github.com/chrisrhayes)**
_Wednesday Nov 30, 2016 at 13:14 GMT_
_Originally opened as https://github.com/overstory/autopilot-potpourri/issues/6_

----

**Comment by chrisrhayes** [comment]
1) Turn into a Python Package
2) RPM

**Comment by chrisrhayes** [comment]
Update at planning meeting:
RPM 'Working' - deploying now. Craig thinks this week.
